services:
  api:
    image: financial-image-app
    container_name: financial-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - "44367:44367" # HTTP mapping
      - "44398:44399" # HTTPS mapping (host:container)
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Docker
  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    expose: 
      - 5432
    volumes:
      - db-volume:/var/lib/postgres
    restart: always
    environment:
      - POSTGRES_DB=FinanciallaunchDB 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
volumes:
  db-volume: